export const Config = {
  // API_URL: 'https://bdiskshunya.shunyaekai.com/',
  API_URL: 'https://disk.shunyaekai.com/',

  createOTPAPI: 'user/createOTP',
  signInAPI: 'user/signin',
  signUpAPI: 'user/signup',
  verifyEmailAPI: 'user/verify_email',
  verifyUsernameAPI: 'user/verify_username',
  verifyMobileAPI: 'user/verify_mobile',
  tailentProfileCreateAPI: 'profile/create',
  getTailentAPI: 'talent/get-talent',
  userSignOutAPI: 'user/signout',
  getProfileAPI: 'profile/getprofile',
  userSelectionFinishAPI: 'user/category-selection',
  showAllPostAPI: 'post',
  profileUpdateAPI: 'profile/update',
  videoRatingAPI: 'post/rating',
  uploadNewVideoAPI: 'post/upload',
  subscriberGetPlansAPI: 'subscriber/get-plans',
  subGetCustomPlanAPI: 'subscriber/get-custom-plans',
  userLogOutAllAPI: 'user/logout-all',
  connectedUsersAPI: 'profile/connect-user-list',
  postDeleteAPI: 'post/delete',
  getsubscriberGetAPI: 'subscriber/get',
  userLocationAPI:'user/location',

  stripePaymentAPI: 'payment/pay',
  stripePaymentCardListAPI: 'payment/list-card',
  stripePaymentDeleteCardAPI: 'payment/delete-card',
  stripePaymentSaveCardAPI: 'payment/add-card',
};

