export const Config = {
  TermsNConditions: 'https://bdiskovered.com/Terms/',
  PrivacyPolicy: 'https://bdiskovered.com/privacy/',
  CommunityURL: 'https://bdiskovered.com/community/',
  // API_URL: 'https://bdiskv1.shunyaekai.com/',
  API_URL: 'https://bdiskv2.bdiskovered.com/',

  // API_URL: 'https://bdiskshunya.shunyaekai.com/',
  // API_URL: 'https://disk.shunyaekai.com/',
  // API_URL: 'https://localbdisk.shunyaekai.com/',

  Google_URL: 'https://maps.googleapis.com/maps/api/geocode/json?latlng=',
  GoogleAPIKEY: 'AIzaSyDHB9O095O9iP0FcAYTGXZKlXGTvxZL5Q8',

  createOTPAPI: 'user/createOTP',
  signInAPI: 'user/signin',
  signUpAPI: 'user/signup',
  verifyEmailAPI: 'user/verify_email',
  verifyUsernameAPI: 'user/verify_username',
  verifyMobileAPI: 'user/verify_mobile',
  tailentProfileCreateAPI: 'profile/create',
  getTailentAPI: 'talent/get-talent',
  userSignOutAPI: 'user/signout',
  getProfileAPI: 'profile/getprofile',
  userSelectionFinishAPI: 'user/category-selection',
  showAllPostAPI: 'post',
  profileUpdateAPI: 'profile/update',
  videoRatingAPI: 'post/rating',
  uploadNewVideoAPI: 'post/upload',
  subscriberGetPlansAPI: 'subscriber/get-plans',
  subGetCustomPlanAPI: 'subscriber/get-custom-plans',
  userLogOutAllAPI: 'user/logout-all',
  connectedUsersAPI: 'profile/connect-user-list',
  postDeleteAPI: 'post/delete',
  getsubscriberGetAPI: 'subscriber/get',
  userLocationAPI: 'user/location',
  changeOwnershipAPI: 'user/change-ownership',
  notificationListAPI: 'profile/notification',
  postFilterAPI: 'post/post-filter',
  boostPostAPI: 'post/post-boost',
  loginSessionAPI: 'user/login-session',
  connectRequestAPI: 'profile/connect-request',
  deactivatAccountAPI: 'user/deactive',
  savedPostAPI: 'post/save-post',
  savedPostListAPI: 'post/save-post-list',
  deleteSavedPostAPI: 'post/delete-save-post',

  blockPostAPI: 'post/block-post',
  blockUserAPI: 'post/block-user',
  reportPostAPI: 'post/report-post',
  blockUserListAPI: 'post/block-user-list',
  unblockUserAPI: 'post/unblock-user',

  inAppPurchaseAPI: 'payment/apple-pay',
  restorePurchaseAPI: 'payment/restore-id',

  stripePaymentAPI: 'payment/pay',
  stripePaymentCardListAPI: 'payment/list-card',
  stripePaymentDeleteCardAPI: 'payment/delete-card',
  stripePaymentSaveCardAPI: 'payment/add-card',
};

